### ISSUE TITLE
igTree performance

### ISSUE THREAD

**Issue by jbacalo** [IgniteUI/igniteui-angularjs#103]
Hi,
Is igTree virtualized? can it support around 100K nodes under a single parent and around 1M nodes total without lagging?
also does it have the option to add selection by checkbox with tri state?

Thanks,
Jonathan

**Comment by kdinev** [comment]
@jbacalo The igTree is not virtualized, so 100k it probably wouldn't be able to handle 100k nodes under a single parent. It really depends on the browser's rendering engine. The help page navigation for Ignite UI is built with an igTree and there it handles ~70k nodes with load on demand:

http://www.igniteui.com/help/

As for a tri-state checkbox, yes that is supported. You need to set `checkboxMode: "triState"`

http://www.igniteui.com/help/api/2016.2/ui.igtree#options:checkboxMode
