### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Tibbersus** [IgniteUI/igniteui-angularjs#116]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Bimob@0.2.0~prestart: Bimob@0.2.0
6 silly lifecycle Bimob@0.2.0~prestart: no script for prestart, continuing
7 info lifecycle Bimob@0.2.0~start: Bimob@0.2.0
8 verbose lifecycle Bimob@0.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle Bimob@0.2.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\site masini lucru\bimob-api\node_modules\.bin;C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36-32\;C:\Deps\qrencode-3.4.4;C:\Deps\boost_1_55_0;C:\Deps\db-4.8.30.NC;C:\MinGW\bin;C:\MinGW\mingw32\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Git\cmd;C:\Program Files\nodejs\;C:\Users\sanis\AppData\Local\Microsoft\WindowsApps;C:\deps\boost_1_57_0>;C:\Users\sanis\AppData\Roaming\npm;C:\Users\sanis\AppData\Local\atom\bin
10 verbose lifecycle Bimob@0.2.0~start: CWD: E:\site masini lucru\bimob-api
11 silly lifecycle Bimob@0.2.0~start: Args: [ '/d /s /c', 'npm run server:dev' ]
12 silly lifecycle Bimob@0.2.0~start: Returned: code: 1  signal: null
13 info lifecycle Bimob@0.2.0~start: Failed to exec start script
14 verbose stack Error: Bimob@0.2.0 start: `npm run server:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Bimob@0.2.0
16 verbose cwd E:\site masini lucru\bimob-api
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error Bimob@0.2.0 start: `npm run server:dev`
22 error Exit status 1
23 error Failed at the Bimob@0.2.0 start script 'npm run server:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Bimob package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Bimob
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Bimob
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mpavlinov** [comment]
I don't see how this call stack is related to the Ignite UI Angular directives. Can you clarify?

**Comment by IG-Stanimir-Dimitrov** [comment]
@Tibbersus , can you please provide context as to how your issue relates to the Ignite UI Angular extensions or should we  close this as not related to the repo content?
