### ISSUE TITLE
igCombo: setter method for the "mode" option

### ISSUE THREAD

**Issue by Cristina-Alboni** [IgniteUI/igniteui-angularjs#117]
I can't find a way in which the "mode" option can be set on the fly.
In the documentation I see only the Get method, not the Set.
[(https://www.igniteui.com/help/api/2017.1/ui.igcombo#options:mode)](https://www.igniteui.com/help/api/2017.1/ui.igcombo#options:mode)

**Comment by kdinev** [comment]
Hi @Cristina-Alboni 

The `mode` option is read-only. The structure of the combo is different in different modes and switching between modes will essentially require re-initializing and re-rendering of the `igCombo`. Changing the `mode` can be done by destroying the current combo, and initializing a new one with the cached configuration, but with changed `mode`.
