### ISSUE TITLE
Can't type spaces (with space bar) in iggrid filter

### ISSUE THREAD

**Issue by TSSchoof** [IgniteUI/igniteui-angularjs#122]
After upgrading to the latest version of igniteui (2017.2, 456) and the latest version of igniteui-angularjs (1.2.1) I can no longer type whitespaces in a filter of an iggrid.

I can type every other possible character, except for spaces. I can type spaces with the alt code (ALT + 32) but **not** with the space bar.

When I create the same grid from JQuery I can type spaces with the space bar.

Below is an example of a very simple grid where this is no longer possible.

>             <ig-grid id="ig-yard"
>                      data-source="main.@Model.DataSource"
>                      width="auto"
>                      height="315px"
>                      auto-commit="true"
>                      auto-generate-columns="false">
>                 <columns>
>                     <column key="key" header-text="Identifier" width="0" data-type="string"></column>
>                     <column key="value" header-text="Name" data-type="string"></column>
>                 </columns>
>                 <features>
>                     <feature name="Filtering" mode="simple" render-filter-button="false"></feature>
>                 </features>
>                 <feature name="Tooltips"
>                          visibility="overflow"
>                          style="popover">
>                 </feature>
>             </ig-grid>

Anything I could be doing wrong / any way to fix this?

**Comment by TSSchoof** [comment]
I have an update for this issue. It was unrelated to the igniteui-angularjs component. 
When I disable the render-filter-button I can type spaces. Enabling it again disables typing spaces.

This seems to be an issue in general with IgniteUI 2017.2: http://jsfiddle.net/t6y6vm60/

Should I post this issue on the website of Infragistics or will you do this?

**Comment by dkamburov** [comment]
Sounds like an issue within filtering of the igGrid, is this only reproducible with AngularJS wrappers ?

**Comment by TSSchoof** [comment]
No, as I said, I was wrong in my assumption: I left out the 'render-filter-button' option in my jquery tests, hence why I thought it was an issue with the wrappers.

**Comment by dkamburov** [comment]
Apologize I edited my comment

**Comment by TSSchoof** [comment]
No problem! Thanks for the feedback. :)
