### ISSUE TITLE
Can't get first step to work [SOLVED]

### ISSUE THREAD

**Issue by dbronk** [IgniteUI/igniteui-angularjs#26]
Hello,

I'm pretty new to JS so please excuse any stupid mistakes.  I've downloaded the igniteui-angular zip and placed on my Windows 7, 64-bit box.  I've installed Node.js for Windows 64-bit.  From my igniteui-angular folder I'm just trying to get the samples going so I run "npm install".  The following is the console output.

D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master>npm install
npm WARN package.json igniteui-angular@ No repository field.
npm ERR! git clone https://github.com/pipobscure/fsevents undefined
npm ERR! git clone https://github.com/pipobscure/fsevents undefined
npm WARN optional dep failed, continuing fsevents@git+https://github.com/pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7
138
\

> ws@0.4.32 install D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master\node_modules\karma\node_modules\so
> cket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
|

\socket.io-client\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin
## \node-gyp.js" rebuild

> phantomjs@1.9.12 install D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master\node_modules\karma-phantomj
> s-launcher\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\Dale-HP\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...
  [==============================----------] 76% 0.0s
Received 7292K total.
Extracting zip contents
Removing D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master\node_modules\karma-phantomjs-launcher\node_mo
dules\phantomjs\lib\phantom
Copying extracted folder C:\Users\Dale-HP\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1416060756747\phantomjs
-1.9.8-windows -> D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master\node_modules\karma-phantomjs-launche
r\node_modules\phantomjs\lib\phantom
Removing C:\Users\Dale-HP\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1416060756747
Writing location.js file
Done. Phantomjs binary available at D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master\node_modules\karma
-phantomjs-launcher\node_modules\phantomjs\lib\phantom\phantomjs.exe

> igniteui-angular@ postinstall D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master
> bower install

[?] May bower anonymously report usage statistics to improve the tool over time? No
bower angular-route#1.2.x       ENOGIT git is not installed or not in the PATH

npm ERR! igniteui-angular@ postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the igniteui-angular@ postinstall script.
npm ERR! This is most likely a problem with the igniteui-angular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls igniteui-angular
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"

npm ERR! cwd D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master\npm-debug.log
npm ERR! not ok code 0

D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master>npm owner ls igniteui-angular
npm ERR! owner ls Couldn't get owner data igniteui-angular
npm ERR! 404 404 Not Found: igniteui-angular
npm ERR! 404
npm ERR! 404 'igniteui-angular' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "owner" "
ls" "igniteui-angular"
npm ERR! cwd D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master\npm-debug.log
npm ERR! not ok code 0

D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master>

The following is from the log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'igniteui-angular' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose node symlink C:\Program Files\nodejs\node.exe
5 verbose request where is /igniteui-angular
6 verbose request registry https://registry.npmjs.org/
7 verbose request id 12c7a2b47d2d47a4
8 verbose url raw /igniteui-angular
9 verbose url resolving [ 'https://registry.npmjs.org/', './igniteui-angular' ]
10 verbose url resolved https://registry.npmjs.org/igniteui-angular
11 verbose request where is https://registry.npmjs.org/igniteui-angular
12 info trying registry request attempt 1 at 09:15:45
13 http GET https://registry.npmjs.org/igniteui-angular
14 http 404 https://registry.npmjs.org/igniteui-angular
15 verbose headers { date: 'Sat, 15 Nov 2014 14:15:46 GMT',
15 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
15 verbose headers   'content-type': 'application/json',
15 verbose headers   'cache-control': 'max-age=0',
15 verbose headers   'content-length': '52',
15 verbose headers   'accept-ranges': 'bytes',
15 verbose headers   via: '1.1 varnish',
15 verbose headers   age: '0',
15 verbose headers   'x-served-by': 'cache-ord1722-ORD',
15 verbose headers   'x-cache': 'MISS',
15 verbose headers   'x-cache-hits': '0',
15 verbose headers   'x-timer': 'S1416060946.082596,VS0,VE30',
15 verbose headers   'keep-alive': 'timeout=10, max=50',
15 verbose headers   connection: 'Keep-Alive' }
16 silly registry.get cb [ 404,
16 silly registry.get   { date: 'Sat, 15 Nov 2014 14:15:46 GMT',
16 silly registry.get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
16 silly registry.get     'content-type': 'application/json',
16 silly registry.get     'cache-control': 'max-age=0',
16 silly registry.get     'content-length': '52',
16 silly registry.get     'accept-ranges': 'bytes',
16 silly registry.get     via: '1.1 varnish',
16 silly registry.get     age: '0',
16 silly registry.get     'x-served-by': 'cache-ord1722-ORD',
16 silly registry.get     'x-cache': 'MISS',
16 silly registry.get     'x-cache-hits': '0',
16 silly registry.get     'x-timer': 'S1416060946.082596,VS0,VE30',
16 silly registry.get     'keep-alive': 'timeout=10, max=50',
16 silly registry.get     connection: 'Keep-Alive' } ]
17 error owner ls Couldn't get owner data igniteui-angular
18 error 404 404 Not Found: igniteui-angular
18 error 404
18 error 404 'igniteui-angular' is not in the npm registry.
18 error 404 You should bug the author to publish it
18 error 404
18 error 404 Note that you can also install from a
18 error 404 tarball, folder, or http url, or git url.
19 error System Windows_NT 6.1.7601
20 error command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "owner" "ls" "igniteui-angular"
21 error cwd D:\user\Dropbox\Windscape\Projects\Ignite-AngularJS\igniteui-angular-master
22 error node -v v0.10.33
23 error npm -v 1.4.28
24 error code E404
25 verbose exit [ 1, true ]

Can any help please?

Sorry to waste your time, but maybe this will help the next person.  I'd been using GitHub Shell for all of my git work.  The issue was simple.  Git was not in my windows path.

**Comment by siddexceed** [comment]
Thanks a lot dbronk. It worked for me as well.
